[project]
name = "zeref-clarity"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.sip-010-trait-v3]
path = "contracts/sip-010-trait.clar"
epoch = "latest"

[contracts.roles-v3]
path = "contracts/roles.clar"
epoch = "latest"

[contracts.ystx-token-v3]
path = "contracts/ystx-token.clar"
epoch = "latest"

[contracts.bridge-adapter-trait-v3]
path = "contracts/bridge-adapter-trait.clar"
epoch = "latest"

[contracts.strategy-registry-v3]
path = "contracts/strategy-registry.clar" 
epoch = "latest"

[contracts.vault-v3]
path = "contracts/vault.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
